luks2: Disable explicit_bzero()
This fixes error:

grub-core/lib/argon2/core.c: In function ‘secure_wipe_memory’:
grub-core/lib/argon2/core.c:135:5: error: implicit declaration of function ‘explicit_bzero’ [-Werror=implicit-function-declaration]
  135 |     explicit_bzero(v, n);
      |     ^~~~~~~~~~~~~~
grub-core/lib/argon2/core.c:135:5: error: nested extern declaration of ‘explicit_bzero’ [-Werror=nested-externs]
cc1: all warnings being treated as errors
make[2]: *** [Makefile:6766: grub-core/lib/argon2/libgrubkern_a-core.o] Error 1

And grub somehow does not use

Add grub does not allow to use <string.h>, thus adding missing include
fails with:

lib/argon2/core.c:30:10: fatal error: string.h: No such file or directory
   30 | #include <string.h>

Fixes: 248be405c ("argon2: Import Argon2 from cryptsetup")

Signed-off-by: Petr Vorel <petr.vorel@gmail.com>